# Generated by Django 3.2.9 on 2021-11-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEggGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField()),
                ('sprite_url', models.URLField(max_length=255)),
                ('flavour_texts', models.JSONField()),
                ('is_legendary', models.BooleanField()),
                ('is_mythical', models.BooleanField()),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.pokemoncolor')),
                ('egg_groups', models.ManyToManyField(null=True, to='pokemon.PokemonEggGroup')),
                ('evolves_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_into', to='pokemon.pokemon')),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.pokemonhabitat')),
                ('shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.pokemonshape')),
                ('types', models.ManyToManyField(null=True, to='pokemon.PokemonType')),
            ],
        ),
    ]
